### ISSUE TITLE
Error in Homebridge logs

### ISSUE THREAD

**Issue by identd113** [OpenGarage/homebridge-og#17]
[2/5/2024, 6:55:49 PM] [Garage] Status garage: closed
[2/5/2024, 6:56:22 PM] [Garage] Error getting state: Error: socket hang up
[2/5/2024, 6:56:22 PM] [Garage] Error polling state RequestError: Error: socket hang up
    at new RequestError (/opt/homebrew/lib/node_modules/homebridge-og/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/homebrew/lib/node_modules/homebridge-og/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/homebrew/lib/node_modules/homebridge-og/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/homebrew/lib/node_modules/homebridge-og/node_modules/request/request.js:185:22)
    at Request.emit (node:events:514:28)
    at Request.onRequestError (/opt/homebrew/lib/node_modules/homebridge-og/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketOnEnd (node:_http_client:519:9)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12) {
  cause: Error: socket hang up
      at connResetException (node:internal/errors:787:14)
      at Socket.socketOnEnd (node:_http_client:519:23)
      at Socket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1589:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  },
  error: Error: socket hang up
      at connResetException (node:internal/errors:787:14)
      at Socket.socketOnEnd (node:_http_client:519:23)
      at Socket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1589:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  },
  options: {
    url: 'http://10.0.1.YY:ZZZZZZ/jc?dkey=XXXXX',
    method: 'GET',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
[2/5/2024, 6:56:28 PM] [Garage] Error getting state: Error: socket hang up

**Comment by identd113** [comment]
This should be resolved by #24, I say, to past me

**Comment by salbahra** [comment]
Thank you @identd113. Closing for now as the PR is merged.
